### SIGN UP
POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
  "username": "allu",
  "password": "passu"
}


### SIGN IN
POST http://localhost:3000/api/auth/signin
Content-Type: application/json

{
  "username": "allu123",
  "password": "passu"
}


### CURRENT USER
GET http://localhost:3000/api/auth/currentuser


### SIGN OUT
POST http://localhost:3000/api/auth/signout
Content-Type: application/json


